"""Pure-library observability sidecar helpers."""

from shared.observability.logger import (
    ObservabilityJsonlAppendLogger,
    file_sha256,
    load_observability_events,
    validate_event_stream,
    write_observability_hash_sidecar_atomic,
    write_observability_summary_atomic,
)
from shared.observability.paths import (
    ObservabilityPaths,
    default_observability_event_path,
    default_observability_hash_path,
    default_observability_summary_path,
    resolve_observability_paths,
    validate_observability_paths,
)
from shared.observability.redaction import (
    ObservabilityRedactionError,
    reject_forbidden_observability_payload,
    sanitize_attributes,
    sanitize_error_summary,
)
from shared.observability.schema import (
    SCHEMA_VERSION,
    ObservabilityArtifactIdentity,
    ObservabilityAttemptIdentity,
    ObservabilityCostEstimate,
    ObservabilityErrorSummary,
    ObservabilityEvent,
    ObservabilityHashSidecar,
    ObservabilityModalContext,
    ObservabilityRowIdentity,
    ObservabilityRunIdentity,
    ObservabilitySummary,
    ObservabilityTokenCounts,
    canonical_event_json,
    canonical_json_bytes,
    row_sha256_from_canonical_json,
    sha256_bytes,
    summary_with_digest,
)

__all__ = [
    "SCHEMA_VERSION",
    "ObservabilityArtifactIdentity",
    "ObservabilityAttemptIdentity",
    "ObservabilityCostEstimate",
    "ObservabilityErrorSummary",
    "ObservabilityEvent",
    "ObservabilityHashSidecar",
    "ObservabilityJsonlAppendLogger",
    "ObservabilityModalContext",
    "ObservabilityPaths",
    "ObservabilityRedactionError",
    "ObservabilityRowIdentity",
    "ObservabilityRunIdentity",
    "ObservabilitySummary",
    "ObservabilityTokenCounts",
    "canonical_event_json",
    "canonical_json_bytes",
    "default_observability_event_path",
    "default_observability_hash_path",
    "default_observability_summary_path",
    "file_sha256",
    "load_observability_events",
    "reject_forbidden_observability_payload",
    "resolve_observability_paths",
    "row_sha256_from_canonical_json",
    "sanitize_attributes",
    "sanitize_error_summary",
    "sha256_bytes",
    "summary_with_digest",
    "validate_event_stream",
    "validate_observability_paths",
    "write_observability_hash_sidecar_atomic",
    "write_observability_summary_atomic",
]
